# 行列演算の基礎

<!-- 1　ベクトルの定義
2　行列の定義
3　転置
4　逆行列
5　行列積 -->

In [1]:
# 1　ベクトルの定義
# 2　行列の定義
# 3　転置
# 4　逆行列
# 5　行列積

In [2]:
import numpy as np

In [3]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [4]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [5]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [6]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [8]:
# 1重カッコだと転置できない
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [9]:
x.T

array([1, 2, 3])

In [10]:
x = np.array([[1, 2, 3]])
x

array([[1, 2, 3]])

In [11]:
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [12]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]
])

In [13]:
print(X)

[[2 3 4]
 [1 2 3]]


In [14]:
X.shape

(2, 3)

In [15]:
row, col = X.shape

In [16]:
row

2

In [17]:
col

3

In [18]:
for x in X:
    print(X)
    print('-----')

[[2 3 4]
 [1 2 3]]
-----
[[2 3 4]
 [1 2 3]]
-----


# 演習問題

In [26]:
# Xの定義
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [27]:
# Yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [28]:
# step1
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [29]:
# step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [30]:
# step3
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [31]:
# step4
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [19]:
import sklearn

In [20]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [21]:
# モデルの宣言
model = LinearRegression()　# fit_intercept=Falseを入れると切片がcoef_の結果に含まれる

In [32]:
# モデルの学習　← パラメータの調整
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
# 調整後のパラメータ
# 傾き
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [34]:
# 切片
model.intercept_

array([-0.14285714])

In [36]:
# 予測制度　← 決定係数
model.score(X, y)

0.6923076923076923

In [38]:
# 予測値の計算
x = np.array([[1, 2, 3]])

In [40]:
y_pred = model.predict(x)
y_pred

array([[3.]])